---
driver:
  name: dokken
  chef_version: 13.8.13
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: centos-6
    driver:
      image: centos:6
      privileged: true
      pid_one_command: /sbin/init
      intermediate_instructions:
      - RUN yum -y install which initscripts
  - name: centos-7
    driver:
      image: centos:7
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
      - RUN yum -y install lsof which net-tools
  - name: ubuntu-1604
    named_run_list: debian
    driver:
      image: ubuntu:16.04
      privileged: true
      pid_one_command: /bin/systemd
      intermediate_instructions: # any tasks before runlist is evaluated and run
      - RUN apt-get -y update && apt-get install -y net-tools curl
      - ENV container docker
      - CMD ['/usr/sbin/init']
  - name: ubuntu-1804
    named_run_list: debian
    driver:
      image: dokken/ubuntu-18.04
      privileged: true
      pid_one_command: /bin/systemd
      intermediate_instructions: # any tasks before runlist is evaluated and run
      - RUN apt-get -y update && apt-get install -y net-tools curl
      - ENV container docker
      - CMD ['/usr/sbin/init']
suites:
  - name: netuitive
    run_list:
      - recipe[netuitive::add_repo]
      - recipe[netuitive::install_agent]
      - recipe[netuitive::configure]
    attributes:
      netuitive:
        custom_collectors:
          FooBarCollector:
            foo: bar
