source 'https://rubygems.org'

gem 'berkshelf', '~> 5.6'
# gem 'chef', '~> 13.8'
gem 'chefspec'
gem 'foodcritic'
gem 'inspec'
gem 'kitchen-docker', '~> 2.5'
gem 'kitchen-dokken', '~> 2.6'
gem 'kitchen-inspec'
gem 'kitchen-vagrant'
gem 'rubocop'
gem 'semver2'
gem 'stove'
gem 'test-kitchen'
